# Generated by Django 5.2.14 on 2026-05-13 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estoque", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="unidadeidentificada",
            name="ano_fabricacao",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
