# Generated by Django 5.2.14 on 2026-05-13 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produtos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="codigo_bndes",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="produto",
            name="codigo_mda",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="produto",
            name="ncm",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
