# Generated by Django 5.2.14 on 2026-05-15 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0001_initial"),
        ("produtos", "0002_produto_codigo_bndes_produto_codigo_mda_produto_ncm"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="chassi",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="produto",
            name="codigo_interno",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddConstraint(
            model_name="produto",
            constraint=models.UniqueConstraint(
                condition=models.Q(("chassi", ""), _negated=True),
                fields=("empresa", "chassi"),
                name="uniq_produto_chassi_por_empresa",
            ),
        ),
    ]
