# Generated by Django 5.2.14 on 2026-05-13 16:26

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="usuario",
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
