# Generated by Django 5.2.14 on 2026-05-13 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="inscricao_estadual",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
